# Generated by Django 4.2.10 on 2024-02-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productattribute_out_of_stoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='out_of_stoke',
            field=models.BooleanField(default=False),
        ),
    ]
