# Generated by Django 4.2.10 on 2024-02-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productattribute_out_of_stoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
