# Generated by Django 4.2.10 on 2024-02-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_delete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='is_delete',
            field=models.BooleanField(null=True),
        ),
    ]
