# Generated by Django 4.2.10 on 2024-02-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productattribute_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
    ]
