# Generated by Django 4.2.10 on 2024-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('initial', 'initial'), ('in_process', 'In Process'), ('deliverd', 'Deliverd'), ('replace', 'Replace'), ('return', 'Return'), ('cancled', 'Cancle')], max_length=20),
        ),
    ]
