# Generated by Django 4.2.30 on 2026-06-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_razorpay_payment_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentevent',
            name='stripe_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
