# Generated by Django 4.2.10 on 2024-02-20 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 20, 8, 7, 16, 630942, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_image',
            field=models.ImageField(default=False, upload_to='static/images'),
        ),
    ]
