# Generated by Django 4.2.10 on 2024-02-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at_product_is_delete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='is_disable',
            new_name='is_display',
        ),
    ]
