# Generated by Django 4.2.10 on 2024-02-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productattribute_is_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='out_of_stoke',
            field=models.BooleanField(default=True),
        ),
    ]
