# Generated by Django 4.2.10 on 2024-02-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
