# Generated by Django 4.2.10 on 2024-02-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.TextField(null=True),
        ),
    ]
